In [1]:
import cv2
url='images/parrot.jpg'
image=cv2.imread(url)
#print numpy array of pixel values
print("Printing .jpg converted to pixel values\n", image)
print("Type of variable image",type(image))
print("Shape of numpy array",image.shape)

Printing .jpg converted to pixel values
 [[[ 88 129  92]
  [ 88 129  92]
  [ 89 130  92]
  ...
  [ 95 108  82]
  [ 93 106  80]
  [ 95 109  85]]

 [[ 90 131  94]
  [ 90 131  94]
  [ 90 131  93]
  ...
  [ 96 109  83]
  [ 94 107  81]
  [ 93 107  83]]

 [[ 92 133  96]
  [ 92 133  96]
  [ 94 133  95]
  ...
  [ 97 110  84]
  [ 95 108  82]
  [ 97 111  87]]

 ...

 [[ 26  21  18]
  [ 26  21  18]
  [ 26  21  18]
  ...
  [232 221 253]
  [232 221 253]
  [231 220 252]]

 [[ 26  21  18]
  [ 26  21  18]
  [ 26  21  18]
  ...
  [232 221 253]
  [232 221 253]
  [231 220 253]]

 [[ 26  21  18]
  [ 26  21  18]
  [ 26  21  18]
  ...
  [230 219 251]
  [229 218 250]
  [231 220 253]]]
Type of variable image <class 'numpy.ndarray'>
Shape of numpy array (1000, 665, 3)


In [ ]:
print("Visualising the Image\n")
cv2.imshow('frame',image)
cv2.waitKey(10)

Visualising the Image



-1

: 

In [2]:
#Write an image to a Directoty (Converting and storing numpy array as a new image file)
cv2.imwrite('images/new_parrot.jpg',image)
print("New image saves as images/new_parrot.jpg")

New image saves as images/new_parrot.jpg


In [ ]:
#Resizing
res_image=cv2.resize(image,(300,500))
print("Shape of Resized image",res_image.shape)
cv2.imshow('frame',res_image)

Shape of Resized image (500, 300, 3)


: 

In [ ]:
#ColorSpace
image_rgb=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
cv2.imshow('RGB',image_rgb)
cv2.waitkey(5)


error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - imshow() missing required argument 'mat' (pos 2)
>  - imshow() missing required argument 'mat' (pos 2)
>  - imshow() missing required argument 'mat' (pos 2)


In [ ]:
#Convert Colorspace BGR to GRAY
image_gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow('GRAY',image_gray)
cv2.waitkey(5)


In [ ]:
#BGR to HSV
image_hsv=cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
cv2.imshow('HSV',image_hsv)
cv2.waitkey(5)

In [ ]:
#Thresholding
image_thresh=cv2.threshold(image_gray,70,255,cv2.THRESH_BINARY)
cv2.imshow('THRESHOLDING',image_thresh)
cv2.waitkey(5)